chore: WIP

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -77,7 +77,18 @@ services:
       - default
       - cron-mon-network
     healthcheck:
-      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
+      test: [
+        "CMD-SHELL",
+        "exec 3<>/dev/tcp/127.0.0.1/8080;\
+        echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;\
+        if [ $? -eq 0 ]; then \
+          echo 'Healthcheck Successful';\
+          exit 0;\
+        else \
+          echo 'Healthcheck Failed'\
+          exit 1;\
+        fi;"
+      ]
       interval: 5s
       timeout: 5s
       retries: 30
