JWT auth (#60)
* feat: Add Keycloak container for local dev

* chore: Reformat healcheck for Keycloak container

* chore: Add `tenant` attribute to JWTs

* refactor: Mode `fairings/` to `infrastrcture/middleware/`

* refactor: Move `response.rs` to `infrastructure/middleware`

* feat: Add new error for auth stuff

* chore: Add `reqwest` as dep

* chore: Add `jsonwebtoken` as dep

* feat: Add error for internal auth errors

* chore: Add `moka` as dep for in-memory caching

* chore: Add `wiremock` as dev-dependency

* feat: Add `JwtAuthService`

* chore: Add `mockall` as dep

* feat: Add `Jwt` guard

* refactor: Move dummy JWT encoding stuff into `test_utils`

* refactor: Make integration test client setup async

* feat: Protect CRUD endpoints via JWTs

* chore: Build with a max of 5 threads for integration tests

* test: Add integration tests to ensure protected routes are indeed protected

* chore: Remove some unnecessary `.to_string()`s

* ci: Install missing deps for running integration tests

* docs: Update OpenAPI spec with JWT auth details

* chore: Missing coverage

* chore: Enable account management in Keycloak

* chore: Move `tenant` mapper to default cron-mon scope and add `aud`

* chore: Accept `cron-mon` as an audience

* docs: Update README

* docs: Fix Markdown panels

* docs: Fix again

* chore: Fix OpenAPI spec

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -39,7 +39,7 @@ services:
   integration-tests-rs:
     extends: rust-cargo
     container_name: rust-integration-tests
-    command: cargo test --no-fail-fast --test "*" -- --test-threads=1
+    command: cargo test --no-fail-fast --jobs=5 --test "*" -- --test-threads=1
     networks:
       - default
       - cron-mon-network
@@ -61,6 +61,38 @@ services:
       timeout: 5s
       retries: 5
     command: [ "postgres", "-c", "log_statement=all" ]
+
+  keycloak:
+    container_name: cron-mon-keycloak
+    image: quay.io/keycloak/keycloak:25.0.2
+    environment:
+      KEYCLOAK_ADMIN: admin
+      KEYCLOAK_ADMIN_PASSWORD: admin
+      KC_HEALTH_ENABLED: true
+    ports:
+      - 8080:8080
+    volumes:
+      - ./keycloak:/opt/keycloak/data/import
+    networks:
+      - default
+      - cron-mon-network
+    healthcheck:
+      test: [
+        "CMD-SHELL",
+        "exec 3<>/dev/tcp/127.0.0.1/8080;\
+        echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;\
+        if [ $? -eq 0 ]; then \
+          echo 'Healthcheck Successful';\
+          exit 0;\
+        else \
+          echo 'Healthcheck Failed'\
+          exit 1;\
+        fi;"
+      ]
+      interval: 5s
+      timeout: 5s
+      retries: 30
+    command: ["start-dev", "--import-realm"]
 
   seeder:
     container_name: cron-mon-db-seeder
@@ -89,8 +121,11 @@ services:
     depends_on:
       db:
         condition: service_healthy
+      keycloak:
+        condition: service_healthy
     environment:
       DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon
+      KEYCLOAK_CERTS_URL: http://cron-mon-keycloak:8080/realms/cron-mon-io/protocol/openid-connect/certs
       CARGO_HOME: /usr/cron-mon/.cargo
     volumes:
       - ./api:/usr/cron-mon/api
@@ -106,9 +141,12 @@ services:
     depends_on:
       db:
         condition: service_healthy
+      keycloak:
+        condition: service_healthy
     environment:
       DATABASE_URL: postgres://cron-mon-api:itsasecret@cron-mon-db/cron-mon
       JSON_LOGGING: true
+      KEYCLOAK_CERTS_URL: http://cron-mon-keycloak:8080/realms/cron-mon-io/protocol/openid-connect/certs
       CARGO_HOME: /usr/cron-mon/.cargo
     volumes:
       - ./api:/usr/cron-mon/api
